language: objective-c

xcode_project: Test.xcodeproj
xcode_scheme: Test
osx_image: xcode8.3
xcode_sdk: iphonesimulator10.1

script:
- ./run-unit-tests.sh 
- if [[ "$TRAVIS_BRANCH" = "release" ]]; then ./build-framework.sh; fi
