language: objective-c

xcode_project: Test.xcodeproj
xcode_scheme: Test
osx_image: xcode8.3
xcode_sdk: iphonesimulator10.1

script:
- ./run-unit-tests.sh 
- if [[ "$TRAVIS_BRANCH" = "release" ]]; then ./build-framework.sh; fi
after_success:
- ./push-framework.sh
env:
  global:
    - TEST_FRAMEWORK_VERSION="1.0.4"
    secure: XvKjjHJ6fkkIrn932Ssvtaw9GopHrd7VV/js2ggGfDFEwfOc1nIvow1hPuxJ7Tbm70Rxvq3HqcCmb5MFLlXLc/XgfkPOtkAmMLTBPTSOYxPkJiJB2dP2K2atw790eFk9Z0/dlgIixRPl0b6Uko4hbNhhyyjAZROiohnLzJlEnha60mj01wm94+wY1Ul7z6qwytDHgKQitvuTqj1erSFG5oyQAynQ/AzPE7dTXxm1XLsJIzqq1LUjTd4McwnyR0CsD8A1xlUq08HbdiicfJbEfoLaiSsKw1fVItxyxcXEd4ZPKSsEjck2pcVi47Y5hK9Y0k9Tc1zTR3oaXjNG+JXYAUn61GSQ5JacfeyiqRKmW3K7KQ2U5IXe2tVo37/s1VElh2rPB50SGfIgNFxVtwby2WNer7BwL5fUNG7eKECvTzmnRR/Lh+xXKBI8F5j9PKEGqwLLp36wh2xGpEnqfJq1C6JZ2VfbW0X7/LQqNI6mt1fZeHvTjlxFXCin4I/9Nu6w+TEfByiQTqm/m7Bzdw5P0zQ1NG4/49Pl072KeFp8h6+AQBUp8WaIxK9WlbDch5/mL4u4oFHk29x46CUzUtRIxHTLkdAtH8UkQMKlD7M+wc+1/dXyGIkduKBV9vmTLDU/LlXtWgtg+G5UAb2dlNFCrLVQncfUC3YDiysXz1Y50J0=

